export const AUTH_USER = 'AUTH_USER';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_MOVIES = 'GET_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';

export const SET_PAGE_COUNT = 'SET_PAGE_COUNT';
export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';
export const GET_MOVIE_PAGE = 'GET_MOVIE_PAGE';

export const ADD_REACTION = 'ADD_REACTION';
export const SET_REACTION = 'SET_REACTION';
export const SET_REACTION_SELECTED = 'SET_REACTION_SELECTED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_SEARCH_PAGE_COUNT = 'SET_SEARCH_PAGE_COUNT';
